[project]
name = "ai-resume-critiquer"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-generativeai>=0.8.5",
    "openai>=1.82.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.1.0",
    "wordcloud>=1.9.2",
    "pandas>=2.1.4",
    "Pillow>=10.1.0",
    "plotly>=5.18.0",
    "PyPDF2>=3.0.1"

]
